### ISSUE TITLE
Blank textbox in firefox on osx

### ISSUE THREAD

**Issue by svermeulen** [glacambre/firenvim#131]
- OS Version: maxOS Mojave 10.14.6
- Browser Version: Firefox Developer Dedition 70.0b11 64 bit
- What I tried to do:  Followed all the install steps, then went to github.com, created a new gitst
- What happened: The text area where the gist is edited appears blank
- What I expected:  To be able to click and use vim in text area

This is with it enabled for the tab:
![image](https://user-images.githubusercontent.com/810762/66099997-0a0fb980-e55e-11e9-8705-e42045c36a03.png)

And with it disabled for the tab:
![image](https://user-images.githubusercontent.com/810762/66100012-1c89f300-e55e-11e9-960d-b47198635091.png)

I also followed the troubleshooting steps and found these errors:

![image](https://user-images.githubusercontent.com/810762/66100121-712d6e00-e55e-11e9-921b-3225e897bb18.png)

**Comment by glacambre** [comment]
The reason this happens is that Github uses a contenteditable element instead of a textarea as their base CodeMirror element. Adding `'gist.github.com': { 'selector': 'textara, *[contenteditable="true"]', 'priority': 1 }` to your `g:firenvim_config` helps firenvim detect the element but the content of the buffer isn't synced on `:w`. Improving codemirror detection should be fairly easy.

**Comment by glacambre** [comment]
Fixed in a722267, except now we're hitting https://bugzilla.mozilla.org/show_bug.cgi?id=1267027 :(

**Comment by glacambre** [comment]
Just to be sure, this only happens on gist.github.com right? Not on txti.es?

**Comment by svermeulen** [comment]
I tried it again this morning after running `PlugUpdate` and couldn't get the previous behaviour anymore (though it still doesn't work).  It just appears as a normal text box for both gists and txti.es

I tried google chrome as well and get errors there too:

![image](https://user-images.githubusercontent.com/810762/66145300-6525c880-e5bf-11e9-8f0a-590cecdb0c77.png)

**Comment by glacambre** [comment]
I see. The errors you're seeing happen because firefox can't run the script that should run neovim.

Could you also check firefox's browser console? (hamburger menu -> web developer -> browser console) There might be different error messages there. If there isn't, could you modify the firenvim script (located in `~/.local/share/firenvim/`) and have it create a random file (e.g. `touch /tmp/firenvim_ran`) before running neovim and redirect nvim's stderr to another file (e.g. `2>/tmp/firenvim_errors`).

Then, try using firenvim twice (e.g. reloading your config twice or clicking on a textarea twice) and see if it creates the two files and if it does, upload `firenvim_errors` here.

**Comment by glacambre** [comment]
I added a new section to the [troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim) about how to start firenvim without an init.vim. I'd like you to try it if you have time :)

**Comment by glacambre** [comment]
I pushed a small modification to this repo. Could you update the neovim plugin and try running `call firenvim#install()` again and see if it fixes anything?

**Comment by svermeulen** [comment]
I tried it again this weekend using google chrome and found everything works great now  :D   Incredible work on this.

**Comment by glacambre** [comment]
So it works in Chrome but not in Firefox?
