### ISSUE TITLE
Cannot `set mouse=`

### ISSUE THREAD

**Issue by ysl2** [glacambre/firenvim#1505]
I found that the `vim.cmd('set mouse=')` cannot work for firenvim.

**Comment by glacambre** [comment]
Huh, indeed, it looks like after complaining about https://github.com/neovim/neovim/issues/11372 I never actually took advantage of the fix.

Thank you for reporting this issue, I'll try to fix it soon.

**Comment by glacambre** [comment]
For now, as a workaround, you can `:map <LeftMouse> <nop>` and `:map <RightMouse> <nop>` in order to disable the mouse :)

**Comment by ysl2** [comment]
Thanks! :)

**Comment by ysl2** [comment]
In fact I want to disable `<MiddleMouse>`, but I found it didn't work after mapping it to `<Nop>`

**Comment by glacambre** [comment]
This is solved in master, the fix will be available to you when I publish a new release on the add-on stores :)

**Comment by martin-braun** [comment]
@glacambre Just a heads up, I tried `vim.opt.mouse = "c"` and `vim.opt.mouse = ""` and it doesn't work.

**Comment by glacambre** [comment]
@martin-braun Thanks for letting me know. It looks like I haven't published a new release since I merged this, I'll try to get it done soon.

**Comment by martin-braun** [comment]
@glacambre No pressure, I'm good with the work-around. I just reported it for the case that there might be still a problem, but failed to see that the last release isn't so young than expected.

Please take your time, stability has more priority. :)
