### ISSUE TITLE
%s/a/b/gc not displaying prompt with neovim nightly

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1661]

**Comment by justinmk** [comment]
could be caused by https://github.com/neovim/neovim/pull/31525 ?

**Comment by antoineco** [comment]
This was seeminly fixed by neovim/neovim#32033

**Comment by glacambre** [comment]
I wouldn't say fixed, but the situation has improved a little indeed. I think Firenvim probably still isn't doing some things right.
