### ISSUE TITLE
Add an external command line UI

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#168]
This is a feature request for a web based command UI external to Neovim (such as a popup overlay to the main UI) that could replace the need for showing the vim command line at all.

See #167 for the poor-man's version of this request, to just hide the vim command line.

**Comment by glacambre** [comment]
Blocked until https://github.com/neovim/neovim/issues/11558 is fixed

**Comment by glacambre** [comment]
I implemented an external commandline in #292. It's not great but does the job. Ideally the external commandline should be displayed outside of the neovim frame, but unfortunately this can't be done efficiently (inter-frame communication is too slow and firenvim already feels pretty slow).

I'll publish a new release next monday.

Feel free to open a new issue if you find bugs/think of ways to improve the external commandline :)

**Comment by glacambre** [comment]
Completely forgot to document it: you need to set a localSetting named `cmdline` to `firenvim` (default is `neovim`) in order to be able to use the external commandline.

**Comment by infokiller** [comment]
Thanks for all the awesome progress! Christmas started a long time ago in firenvim!
The Neovim issue you referenced above (https://github.com/neovim/neovim/issues/11558) is still not fixed. So will this still work?

**Comment by glacambre** [comment]
Yep, it'll work. I thought it would be a blocking issue as I didn't understand correctly what was going on. bfredl's explanations corrected my misconceptions and I realized that this was really a minor issue - the replace confirmation prompt you get with `%s/x/y/c` will just stay longer than it should and this issue will disappear from firenvim by itself once the problem is fixed in neovim :)
