### ISSUE TITLE
at-sign on Swedish keyboard layout (also, dead keys)

### ISSUE THREAD

**Issue by simmel** [glacambre/firenvim#202]
- OS Version: Mac OS X 10.14.6
- Browser Version: Firefox 71.0b6 (64-bit)
- What I tried to do: Type `@[]` on with the `Swedish - Pro` layout which is alt/opt+2, 8 or 9. Seems like "dead keys" are an issue as well (like I can't type `é` since that requires me to type shift+´+e).
- What happened: It hits escape to take me out of insert mode, I suspect, and then types the at-sign in case of alt/opt+2.

Scandinavian and German keyboard layouts are the ones that I know which uses dead keys and often comes up in keyboard layout related issues = )

Thank you for this plugin, I've used other related plugins before but this one really takes the price!

**Comment by glacambre** [comment]
I pushed a new version (v0.1.12) that should handle composed characters better this morning, what firenvm version did you try? If you tried v0.1.12, could you try v0.1.11 and tel me if that makes a difference?

This is a rather surprising issue because I use a french layout and often use dead keys (â, è, I even use it to type emojis 💩) and firenvim handles these well.

**Comment by simmel** [comment]
`é` now works, but still not @. See [this video](https://stockholmuniversity.box.com/shared/static/e4lgi93iiizv1dxfu9kwo0xxn02s0z8b.mp4)

**Comment by glacambre** [comment]
Are you sure you (or a plugin) didn't remap `@` to something else? It looks like firenvim is correctly registering `@` symbols. Running `:map @` in firenvim should be enough to see if `@` is mapped to something.


If `@` isn't remapped to anything, could you go through the following steps?
1) Click on any textarea in order to make the firenvim frame pop up
2) Open your browser's debugger, navigate to the "source code"/"debugger" tab
3) In this tab, find Firenvim's source code. Select "NeovimFrame.ts" if it is present, "nvimui.js" if it isn't.
4) Search (usually bound to `<C-f>`) for `addEventListener("keydown`. This should give you a single result. Place a log point (this can be done by clicking in the number column) on the line below. The content of this log should be `evt`.
5) Search for `addEventListener("input` and also place a logpoint logging `evt` on the line below.
6) Go back to the neovim frame. Press `a` to enter insert mode. Then repeat whatever key sequence you need to press in order to insert an `@`.
7) Go to the `Console` tab of the debugger. Expand each event once by clicking on the grey arrow that resides at the beginning of each line. Then, copy each event here.

**Comment by simmel** [comment]
```
:map @
No mapping found
```

```
keydown
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyI"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "i"
keyCode: 73
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 231147
type: "keydown"
view: Window moz-extension://33571ab2-432f-a04c-a83a-dae9c7d0bb55/NeovimFrame.html
which: 73
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), … }
NeovimFrame.ts:173:12

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltRight"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 2
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 237953
type: "keydown"
view: Window moz-extension://33571ab2-432f-a04c-a83a-dae9c7d0bb55/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), … }
NeovimFrame.ts:173:12

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "Digit2"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "@"
keyCode: 50
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: false
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 238216
type: "keydown"
view: Window moz-extension://33571ab2-432f-a04c-a83a-dae9c7d0bb55/NeovimFrame.html
which: 50
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), … }
```

**Comment by glacambre** [comment]
I published a new release a fix for your `@` problem, could you update to v0.1.14 and let me know if the issue disappeared? :)

**Comment by simmel** [comment]
Yes, it works now! Thanks!

If I hold opt/alt and press shift the text "Shift" gets inserted though, 
not a big deal but I suspect it's a bug = )

Thank you again!

**Comment by glacambre** [comment]
Thanks :)

**Comment by glacambre** [comment]
Could you give me another log, like https://github.com/glacambre/firenvim/issues/202#issuecomment-552309907, but showing the events that happen when you press opt/alt + shift?

**Comment by simmel** [comment]
```
keydown
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyI"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "i"
keyCode: 73
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 105790
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 73
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 107967
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "Digit2"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "@"
keyCode: 50
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: false
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 108251
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 50
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 112096
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "Digit2"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "@"
keyCode: 50
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: false
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 112335
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 50
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyI"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "i"
keyCode: 73
layerX: 0
layerY: 0
location: 0
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 125807
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 73
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 129673
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt-Shift
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "ShiftLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Shift"
keyCode: 16
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: false
shiftKey: true
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 130068
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 16
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 134283
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Shift
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "ShiftLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Shift"
keyCode: 16
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: true
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 134933
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 16
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt-Shift
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: true
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 135216
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "AltLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Alt"
keyCode: 18
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: true
shiftKey: false
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 135643
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 18
<get isTrusted()>: function isTrusted()
<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), initKeyEvent: initKeyEvent(), ɠ}
NeovimFrame.ts:196:16

keydown Alt-Shift
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "ShiftLeft"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
explicitOriginalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
isComposing: false
isTrusted: true
key: "Shift"
keyCode: 16
layerX: 0
layerY: 0
location: 1
metaKey: false
originalTarget: <textarea id="keyhandler" style="left: 0px; top: 0px;">
rangeOffset: 0
rangeParent: null
repeat: false
returnValue: false
shiftKey: true
target: <textarea id="keyhandler" style="left: 0px; top: 0px;">
timeStamp: 135827
type: "keydown"
view: Window moz-extension://d62f62e1-c9ea-3d43-8d26-78367e7cbb1b/NeovimFrame.html
which: 16
<get isTrusted()>: function isTrusted()
```

**Comment by simmel** [comment]
Now in 0.1.15 `@` doesn't work again but maybe you removed it since it was an incomplete fix?

HTH

**Comment by glacambre** [comment]
>Now in 0.1.15 @ doesn't work again but maybe you removed it since it was an incomplete fix?

No, I didn't change anything related to keyboard handling between 0.1.14 and 0.1.15 :(.

Thanks for posting this log. I'll do my best to fix this issue before releasing 0.1.16.

**Comment by glacambre** [comment]
I think the reason `@` doesn't work anymore for you is that you used the left Alt key rather than the right one. I didn't know you could also press LeftAlt to produce special characters (on french keyboards only the right alt key is used for special characters, the left one behaves more like Control/Super).

**Comment by glacambre** [comment]
Hi, could you try to [build](https://github.com/glacambre/firenvim#from-source) #266, set [the required setting](https://github.com/glacambre/firenvim/pull/266/files#diff-04c6e90faac2675aa89e2176d2eec7d8R173-R184) in your config and see if this lets you type special characters?
If #266 does fix your problem, I'd also like to have your input about making the documentation for this setting clearer, I'm not very satisfied with it for now.

**Comment by simmel** [comment]
> Hi, could you try to [build](https://github.com/glacambre/firenvim#from-source) #266, set [the required setting](https://github.com/glacambre/firenvim/pull/266/files#diff-04c6e90faac2675aa89e2176d2eec7d8R173-R184) in your config and see if this lets you type special characters?

`@é[]≈{}` looks like everything works = )

Btw, your instructions on how to install the addon from file doesn't work and seems to be outdated. https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/ works very well for me.

> If #266 does fix your problem, I'd also like to have your input about making the documentation for this setting clearer, I'm not very satisfied with it for now.

I think the documentation is clear but it's a very weird thing that you have to do it.
Using an <A-@> mapping in Vim maybe isn't that common so you can just ignore it and document it as a limitation (like with <C-W>)?
Having to set that globalSetting is fine for me.

Thank you for investing time into both this addon and my issue!

**Comment by glacambre** [comment]
>I think the documentation is clear but it's a very weird thing that you have to do it.
>Using an <A-@> mapping in Vim maybe isn't that common so you can just ignore it and document it as a limitation (like with )?

I agree, it would be better if things "just worked". I think I'll just set this setting to "alphanum" by default on OSX and leave windows and linux untouched.

Thanks for reporting this issue, providing logs, trying this PR out and for everything else :).

**Comment by simmel** [comment]
On Wed, 2019-11-27 at 11:33:13 -0800, Ghjuvan Lacambre wrote:
>>I think the documentation is clear but it's a very weird thing that you have to do it.
>>Using an <A-@> mapping in Vim maybe isn't that common so you can just ignore it and document it as a limitation (like with )?
>
>I agree, it would be better if things "just worked". I think I'll just set this setting to "alphanum" by default on OSX and leave windows and linux untouched.

Sounds like a great idea!

>Thanks for reporting this issue, providing logs, trying this PR out and 
>for everything else :).

No problem! Keep up the good work!

**Comment by glacambre** [comment]
I published v0.1.16, which contains the fix for this issue, yesterday (sorry it took so long!). Please let me know if you're encountering other problems :)
