### ISSUE TITLE
nvim.exe does not exit after chrome exit

### ISSUE THREAD

**Issue by Bakudankun** [glacambre/firenvim#624]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 83.0.4103.116
- Browser Addon Version: 0.1.29
- Neovim Plugin Version: 0.1.29
- What I tried to do:
  - Reboot machine
  - Open chrome and close (with topright X button) five times
  - Open Task Manager and go to the "Details" tab
- What happened:
You can see five nvim.exe processes are running

with no init.vim nor other plugins (than firenvim).
I'm not sure if this issue is Windows-specific.

**Comment by glacambre** [comment]
Hi - thanks for the report. Looks like https://github.com/glacambre/firenvim/issues/493 is coming back from the dead to haunt us :/.

Testing on windows is a bit hard for me at the moment so it might take a while for me to fix this issue.

**Comment by JW9506** [comment]
```bash
#!/bin/bash
for name in $(tasklist | grep nvim | awk '{print $2}'); do
    taskkill -pid $name -f -t
done
```
I use this to kill all the nvim.exe after `firenvim` usage. Is there any work around?

**Comment by Bakudankun** [comment]
Maybe related to Neovim version. I forgot to write down but I think this issue was resolved when I updated Neovim to v0.4.4 from previous version.
Could you test with v0.4.4?

**Comment by JW9506** [comment]
@Bakudankun I just tried `NVIM v0.5.0-828-g0a95549d6` the latest available from the repo and the problem persists, and now I will give 0.4.4 a try.

**Comment by Bakudankun** [comment]
I don't know why; in my environment nvim.exe will disappear from Task Manager after closing Chrome.

Note: my current environment:
OS Version: win x86-64
Neovim Version: NVIM v0.4.4 (installed with scoop)
Browser Version: Google Inc. Chrome 86.0.4240.198
Browser Addon Version: 0.1.32
Neovim Plugin Version: v0.1.32

**Comment by JW9506** [comment]
@Bakudankun w/e, looks like it is only a problem with chrome, I will start using firefox once it starts to bother me.

**Comment by glacambre** [comment]
Thanks for the report @JW9506, I'll investigate.

**Comment by glacambre** [comment]
@JW9506 Can you still reproduce this issue with Firenvim 0.2.4 (make sure you've updated both the browser plugin and the neovim plugin)? I couldn't with Chrome, Edge and Firefox.

**Comment by glacambre** [comment]
This issue has been waiting for feedback for a month and a half now so I'll close it. Feel free to complain if you still encounter this bug - I'll reopen :)
